# What is PyTorch?

In [1]:
from __future__ import print_function
import torch

In [2]:
# construct a 5x3 matrix, uninitialized
x = torch.empty(5,3)
print(x)

tensor([[-4.4945e+21,  6.4039e-43, -4.4943e+21],
        [ 6.4039e-43, -4.4950e+21,  6.4039e-43],
        [-4.4950e+21,  6.4039e-43, -4.4951e+21],
        [ 6.4039e-43, -4.4951e+21,  6.4039e-43],
        [-4.4953e+21,  6.4039e-43, -4.4953e+21]])


In [3]:
# construct a randomly initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.2823, 0.6028, 0.0733],
        [0.2297, 0.2551, 0.7167],
        [0.5081, 0.6558, 0.6764],
        [0.0641, 0.0634, 0.0521],
        [0.5270, 0.0310, 0.4109]])


In [4]:
# construct a matrix filled zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# create a tensor based on an existing tensor.
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.4350,  0.4359,  0.5994],
        [ 0.2300, -1.5181,  0.7247],
        [ 0.0740, -0.3288,  0.0211],
        [ 1.2802, -0.8478, -0.2568],
        [-0.0920,  0.0570, -1.5191]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 2.4224,  0.8341,  1.1412],
        [ 0.7867, -1.0790,  1.0613],
        [ 0.0913,  0.3534,  0.6212],
        [ 1.3456, -0.5715, -0.2529],
        [ 0.0481,  0.6858, -1.4350]])


In [10]:
print(torch.add(x, y))

tensor([[ 2.4224,  0.8341,  1.1412],
        [ 0.7867, -1.0790,  1.0613],
        [ 0.0913,  0.3534,  0.6212],
        [ 1.3456, -0.5715, -0.2529],
        [ 0.0481,  0.6858, -1.4350]])


In [14]:
# Addition: providing an output tensor as argument
result = torch.empty(5,3)
torch.add(x, y, out=result)

tensor([[ 2.4224,  0.8341,  1.1412],
        [ 0.7867, -1.0790,  1.0613],
        [ 0.0913,  0.3534,  0.6212],
        [ 1.3456, -0.5715, -0.2529],
        [ 0.0481,  0.6858, -1.4350]])

In [15]:
result

tensor([[ 2.4224,  0.8341,  1.1412],
        [ 0.7867, -1.0790,  1.0613],
        [ 0.0913,  0.3534,  0.6212],
        [ 1.3456, -0.5715, -0.2529],
        [ 0.0481,  0.6858, -1.4350]])

In [18]:
# in-place
# adds x to y
y.add_(x)
print(y)

tensor([[ 5.2924,  1.7059,  2.3401],
        [ 1.2466, -4.1152,  2.5107],
        [ 0.2393, -0.3041,  0.6635],
        [ 3.9059, -2.2672, -0.7666],
        [-0.1358,  0.7998, -4.4732]])


Any operation that mutates a tensor in-place is post-fixed with an `_`.
For example: `x.copy_(y)`, `x.t_()`, will change x.

In [19]:
print(x[:,1])

tensor([ 0.4359, -1.5181, -0.3288, -0.8478,  0.0570])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`

In [20]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
x

tensor([[ 0.4860,  0.4813,  1.0297, -0.1130],
        [ 0.0610,  1.6759, -1.8731, -1.2833],
        [-0.3535, -1.7037,  0.2077, -1.6297],
        [-1.0432, -0.8187,  1.9121, -1.6254]])

In [21]:
z

tensor([[ 0.4860,  0.4813,  1.0297, -0.1130,  0.0610,  1.6759, -1.8731, -1.2833],
        [-0.3535, -1.7037,  0.2077, -1.6297, -1.0432, -0.8187,  1.9121, -1.6254]])

In [23]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4817])
-0.48165708780288696


## Converting a Torch Tensor to a NumPy Array
The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically

In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
torch.cuda.is_available()

False